[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
blue_carbon_registry = "6q7u2DH9vswSbpPYZLyaamAyBXQeXBCPfcgmi1dikuQB"

[programs.devnet]
blue_carbon_registry = "GDEzy7wZw5VqSpBr9vDHiMiFa9QahNeZ8UfETMfVPakr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
