# DEPLOYMENTS DISABLED
# All workflows and deployments are temporarily disabled
# To re-enable: replace this file with proper workflow configuration

name: Disabled Pipeline

on:
  workflow_dispatch: # Only manual trigger, no automatic triggers

jobs:
  disabled:
    runs-on: ubuntu-latest
    name: "All Deployments Disabled"
    
    steps:
    - name: Deployment Status
      run: |
        echo "🚫 All deployments and workflows are currently DISABLED"
        echo "ℹ️  No automatic deployments will occur"
        echo "✅ Repository is in development-only mode"

